
// Generated by Cadence Genus(TM) Synthesis Solution 19.10-p002_1
// Generated on: Oct 21 2020 09:13:10 IST (Oct 21 2020 03:43:10 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, count, SE, scan_in, scan_out);
  input clk, rst, SE, scan_in;
  output [7:0] count;
  output scan_out;
  wire clk, rst, SE, scan_in;
  wire [7:0] count;
  wire scan_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  assign scan_out = count[7];
  SDFFRHQX1 \count_reg[7] (.RN (rst), .CK (clk), .D (n_13), .SI
       (count[6]), .SE (SE), .Q (count[7]));
  SDFFRHQX1 \count_reg[6] (.RN (rst), .CK (clk), .D (n_12), .SI
       (count[5]), .SE (SE), .Q (count[6]));
  SDFFRHQX1 \count_reg[5] (.RN (rst), .CK (clk), .D (n_9), .SI
       (count[4]), .SE (SE), .Q (count[5]));
  XNOR2X1 g199__8780(.A (count[7]), .B (n_11), .Y (n_13));
  OA21X1 g201__4296(.A0 (count[6]), .A1 (n_10), .B0 (n_11), .Y (n_12));
  SDFFRHQX1 \count_reg[4] (.RN (rst), .CK (clk), .D (n_8), .SI
       (count[3]), .SE (SE), .Q (count[4]));
  NAND2X1 g203__3772(.A (count[6]), .B (n_10), .Y (n_11));
  AOI2BB1X1 g204__1474(.A0N (count[5]), .A1N (n_7), .B0 (n_10), .Y
       (n_9));
  SDFFRHQX1 \count_reg[3] (.RN (rst), .CK (clk), .D (n_5), .SI
       (count[2]), .SE (SE), .Q (count[3]));
  SDFFRHQX1 \count_reg[2] (.RN (rst), .CK (clk), .D (n_3), .SI
       (count[1]), .SE (SE), .Q (count[2]));
  AOI2BB1X1 g207__4547(.A0N (count[4]), .A1N (n_6), .B0 (n_7), .Y
       (n_8));
  AND2XL g206__9682(.A (count[5]), .B (n_7), .Y (n_10));
  AND2XL g209__2683(.A (count[4]), .B (n_6), .Y (n_7));
  AOI2BB1XL g210__1309(.A0N (count[3]), .A1N (n_4), .B0 (n_6), .Y
       (n_5));
  SDFFRHQX1 \count_reg[1] (.RN (rst), .CK (clk), .D (n_2), .SI
       (count[0]), .SE (SE), .Q (count[1]));
  AND2XL g212__6877(.A (count[3]), .B (n_4), .Y (n_6));
  AOI2BB1X1 g213__2900(.A0N (count[2]), .A1N (n_1), .B0 (n_4), .Y
       (n_3));
  SDFFRHQX1 \count_reg[0] (.RN (rst), .CK (clk), .D (n_0), .SI
       (scan_in), .SE (SE), .Q (count[0]));
  AOI2BB1X1 g216__2391(.A0N (count[1]), .A1N (count[0]), .B0 (n_1), .Y
       (n_2));
  AND2XL g215__7675(.A (count[2]), .B (n_1), .Y (n_4));
  NOR2BX1 g218__7118(.AN (count[1]), .B (n_0), .Y (n_1));
  INVX1 g219(.A (count[0]), .Y (n_0));
endmodule

