set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports hSync]
set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports vSync]
set_property PACKAGE_PIN W5 [get_ports i_clk]
set_property IOSTANDARD LVCMOS33 [get_ports i_clk]

# define ext pll clock as 100 MHz for timing check
create_clock -period 10.000 -name ext_pll_in [get_ports i_clk]

set_property PACKAGE_PIN N19 [get_ports {red[3]}]
set_property PACKAGE_PIN J19 [get_ports {red[2]}]
set_property PACKAGE_PIN H19 [get_ports {red[1]}]
set_property PACKAGE_PIN G19 [get_ports {red[0]}]
set_property PACKAGE_PIN D17 [get_ports {green[3]}]
set_property PACKAGE_PIN G17 [get_ports {green[2]}]
set_property PACKAGE_PIN H17 [get_ports {green[1]}]
set_property PACKAGE_PIN J17 [get_ports {green[0]}]
set_property PACKAGE_PIN J18 [get_ports {blue[3]}]
set_property PACKAGE_PIN K18 [get_ports {blue[2]}]
set_property PACKAGE_PIN L18 [get_ports {blue[1]}]
set_property PACKAGE_PIN N18 [get_ports {blue[0]}]
set_property PACKAGE_PIN P19 [get_ports hSync]
set_property PACKAGE_PIN R19 [get_ports vSync]

set_property IOSTANDARD LVCMOS33 [get_ports mmu_we]
set_property PACKAGE_PIN V19 [get_ports mmu_we]
set_property IOSTANDARD LVCMOS33 [get_ports ram_enable]
set_property PACKAGE_PIN U19 [get_ports ram_enable]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_enable]
set_property PACKAGE_PIN E19 [get_ports lcd_enable]
set_property IOSTANDARD LVCMOS33 [get_ports display_enable]
set_property PACKAGE_PIN U16 [get_ports display_enable]

set_property IOSTANDARD LVCMOS33 [get_ports clk_source]
set_property PACKAGE_PIN T1 [get_ports clk_source]
set_property IOSTANDARD LVCMOS33 [get_ports clk_button]
set_property PACKAGE_PIN U18 [get_ports clk_button]


set_property IOSTANDARD LVCMOS33 [get_ports rst_indicator]
set_property PACKAGE_PIN L1 [get_ports rst_indicator]
set_property IOSTANDARD LVCMOS33 [get_ports clk_indicator]
set_property PACKAGE_PIN P1 [get_ports clk_indicator]

set_property PACKAGE_PIN R2 [get_ports i_reset]
set_property IOSTANDARD LVCMOS33 [get_ports i_reset]

set_property PACKAGE_PIN U2 [get_ports {anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segement[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segement[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segement[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segement[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segement[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segement[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segement[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segement[0]}]
set_property PACKAGE_PIN W7 [get_ports {segement[7]}]
set_property PACKAGE_PIN W6 [get_ports {segement[6]}]
set_property PACKAGE_PIN U8 [get_ports {segement[5]}]
set_property PACKAGE_PIN V8 [get_ports {segement[4]}]
set_property PACKAGE_PIN U5 [get_ports {segement[3]}]
set_property PACKAGE_PIN V5 [get_ports {segement[2]}]
set_property PACKAGE_PIN V7 [get_ports {segement[0]}]
set_property PACKAGE_PIN U7 [get_ports {segement[1]}]

create_generated_clock -name cpu_clk_div/cpu_clk -source [get_ports i_clk] -divide_by 16 [get_pins cpu_clk_div/out_clk_reg/Q]
create_generated_clock -name graphics_engine/display_driver/pixelClockDivider/out_clk_reg_0 -source [get_ports i_clk] -divide_by 2 [get_pins graphics_engine/display_driver/pixelClockDivider/out_clk_reg/Q]
create_generated_clock -name lcd/mux/selectClockDivider/out_clk -source [get_ports i_clk] -divide_by 1000 [get_pins lcd/mux/selectClockDivider/out_clk_reg/Q]
