#=========================================================================
# ASIC Design Kit -- FreePDK45 + NanGate Open Cell Library
#=========================================================================
# Author : Christopher Torng
# Date   : June 7, 2019
#

name: freepdk-45nm

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - adk

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # If standard view is selected, download the full pkg (~17MB)
  - if [[ x{adk_view} == xview-standard ]]; then
      wget https://github.com/mflowgen/freepdk-45nm/archive/master.zip;
      unzip master.zip;
      mv freepdk-45nm-master view-standard;
    fi
  # Set up the outputs
  - mkdir -p outputs && cd outputs
  - ln -sf ../{adk_view} adk

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  adk: freepdk-45nm
  adk_view: view-tiny

#-------------------------------------------------------------------------
# Special mflowgen tags
#-------------------------------------------------------------------------

sandbox: False


