# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/youssef/Documents/mcu-soc/rapidx_basys3/rapidx_basys3.srcs/sources_1/ip/blk_mem_ram/blk_mem_ram.xci
# IP: The module: 'blk_mem_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/youssef/Documents/mcu-soc/rapidx_basys3/rapidx_basys3.gen/sources_1/ip/blk_mem_ram/blk_mem_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/youssef/Documents/mcu-soc/rapidx_basys3/rapidx_basys3.srcs/sources_1/ip/blk_mem_ram/blk_mem_ram.xci
# IP: The module: 'blk_mem_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/youssef/Documents/mcu-soc/rapidx_basys3/rapidx_basys3.gen/sources_1/ip/blk_mem_ram/blk_mem_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
