# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/blk_vram_gen_0/blk_vram_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_vram_gen_0 || ORIG_REF_NAME==blk_vram_gen_0} -quiet] -quiet

# IP: ip/blk_cpu_mem/blk_cpu_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_cpu_mem || ORIG_REF_NAME==blk_cpu_mem} -quiet] -quiet
