
//input ports
add mapped point i_pc[31] i_pc[31] -type PI PI
add mapped point i_pc[30] i_pc[30] -type PI PI
add mapped point i_pc[29] i_pc[29] -type PI PI
add mapped point i_pc[28] i_pc[28] -type PI PI
add mapped point i_pc[27] i_pc[27] -type PI PI
add mapped point i_pc[26] i_pc[26] -type PI PI
add mapped point i_pc[25] i_pc[25] -type PI PI
add mapped point i_pc[24] i_pc[24] -type PI PI
add mapped point i_pc[23] i_pc[23] -type PI PI
add mapped point i_pc[22] i_pc[22] -type PI PI
add mapped point i_pc[21] i_pc[21] -type PI PI
add mapped point i_pc[20] i_pc[20] -type PI PI
add mapped point i_pc[19] i_pc[19] -type PI PI
add mapped point i_pc[18] i_pc[18] -type PI PI
add mapped point i_pc[17] i_pc[17] -type PI PI
add mapped point i_pc[16] i_pc[16] -type PI PI
add mapped point i_pc[15] i_pc[15] -type PI PI
add mapped point i_pc[14] i_pc[14] -type PI PI
add mapped point i_pc[13] i_pc[13] -type PI PI
add mapped point i_pc[12] i_pc[12] -type PI PI
add mapped point i_pc[11] i_pc[11] -type PI PI
add mapped point i_pc[10] i_pc[10] -type PI PI
add mapped point i_pc[9] i_pc[9] -type PI PI
add mapped point i_pc[8] i_pc[8] -type PI PI
add mapped point i_pc[7] i_pc[7] -type PI PI
add mapped point i_pc[6] i_pc[6] -type PI PI
add mapped point i_pc[5] i_pc[5] -type PI PI
add mapped point i_pc[4] i_pc[4] -type PI PI
add mapped point i_pc[3] i_pc[3] -type PI PI
add mapped point i_pc[2] i_pc[2] -type PI PI
add mapped point i_pc[1] i_pc[1] -type PI PI
add mapped point i_pc[0] i_pc[0] -type PI PI
add mapped point i_control_signal.rd[4] i_control_signal[rd][4] -type PI PI
add mapped point i_control_signal.rd[3] i_control_signal[rd][3] -type PI PI
add mapped point i_control_signal.rd[2] i_control_signal[rd][2] -type PI PI
add mapped point i_control_signal.rd[1] i_control_signal[rd][1] -type PI PI
add mapped point i_control_signal.rd[0] i_control_signal[rd][0] -type PI PI
add mapped point i_control_signal.rs2[4] i_control_signal[rs2][4] -type PI PI
add mapped point i_control_signal.rs2[3] i_control_signal[rs2][3] -type PI PI
add mapped point i_control_signal.rs2[2] i_control_signal[rs2][2] -type PI PI
add mapped point i_control_signal.rs2[1] i_control_signal[rs2][1] -type PI PI
add mapped point i_control_signal.rs2[0] i_control_signal[rs2][0] -type PI PI
add mapped point i_control_signal.rs1[4] i_control_signal[rs1][4] -type PI PI
add mapped point i_control_signal.rs1[3] i_control_signal[rs1][3] -type PI PI
add mapped point i_control_signal.rs1[2] i_control_signal[rs1][2] -type PI PI
add mapped point i_control_signal.rs1[1] i_control_signal[rs1][1] -type PI PI
add mapped point i_control_signal.rs1[0] i_control_signal[rs1][0] -type PI PI
add mapped point i_control_signal.fcs_opcode[2] i_control_signal[fcs_opcode][2] -type PI PI
add mapped point i_control_signal.fcs_opcode[1] i_control_signal[fcs_opcode][1] -type PI PI
add mapped point i_control_signal.fcs_opcode[0] i_control_signal[fcs_opcode][0] -type PI PI
add mapped point i_control_signal.rs2_out i_control_signal[rs2_out] -type PI PI
add mapped point i_control_signal.rs1_out i_control_signal[rs1_out] -type PI PI
add mapped point i_control_signal.iop i_control_signal[iop] -type PI PI
add mapped point i_control_signal.alu_reg i_control_signal[alu_reg] -type PI PI
add mapped point i_control_signal.alu_imm i_control_signal[alu_imm] -type PI PI
add mapped point i_control_signal.mem i_control_signal[mem] -type PI PI
add mapped point i_control_signal.cond_branch i_control_signal[cond_branch] -type PI PI
add mapped point i_control_signal.uncond_branch i_control_signal[uncond_branch] -type PI PI
add mapped point i_control_signal.load_upper_imm i_control_signal[load_upper_imm] -type PI PI
add mapped point i_rs1[31] i_rs1[31] -type PI PI
add mapped point i_rs1[30] i_rs1[30] -type PI PI
add mapped point i_rs1[29] i_rs1[29] -type PI PI
add mapped point i_rs1[28] i_rs1[28] -type PI PI
add mapped point i_rs1[27] i_rs1[27] -type PI PI
add mapped point i_rs1[26] i_rs1[26] -type PI PI
add mapped point i_rs1[25] i_rs1[25] -type PI PI
add mapped point i_rs1[24] i_rs1[24] -type PI PI
add mapped point i_rs1[23] i_rs1[23] -type PI PI
add mapped point i_rs1[22] i_rs1[22] -type PI PI
add mapped point i_rs1[21] i_rs1[21] -type PI PI
add mapped point i_rs1[20] i_rs1[20] -type PI PI
add mapped point i_rs1[19] i_rs1[19] -type PI PI
add mapped point i_rs1[18] i_rs1[18] -type PI PI
add mapped point i_rs1[17] i_rs1[17] -type PI PI
add mapped point i_rs1[16] i_rs1[16] -type PI PI
add mapped point i_rs1[15] i_rs1[15] -type PI PI
add mapped point i_rs1[14] i_rs1[14] -type PI PI
add mapped point i_rs1[13] i_rs1[13] -type PI PI
add mapped point i_rs1[12] i_rs1[12] -type PI PI
add mapped point i_rs1[11] i_rs1[11] -type PI PI
add mapped point i_rs1[10] i_rs1[10] -type PI PI
add mapped point i_rs1[9] i_rs1[9] -type PI PI
add mapped point i_rs1[8] i_rs1[8] -type PI PI
add mapped point i_rs1[7] i_rs1[7] -type PI PI
add mapped point i_rs1[6] i_rs1[6] -type PI PI
add mapped point i_rs1[5] i_rs1[5] -type PI PI
add mapped point i_rs1[4] i_rs1[4] -type PI PI
add mapped point i_rs1[3] i_rs1[3] -type PI PI
add mapped point i_rs1[2] i_rs1[2] -type PI PI
add mapped point i_rs1[1] i_rs1[1] -type PI PI
add mapped point i_rs1[0] i_rs1[0] -type PI PI
add mapped point i_rs2[31] i_rs2[31] -type PI PI
add mapped point i_rs2[30] i_rs2[30] -type PI PI
add mapped point i_rs2[29] i_rs2[29] -type PI PI
add mapped point i_rs2[28] i_rs2[28] -type PI PI
add mapped point i_rs2[27] i_rs2[27] -type PI PI
add mapped point i_rs2[26] i_rs2[26] -type PI PI
add mapped point i_rs2[25] i_rs2[25] -type PI PI
add mapped point i_rs2[24] i_rs2[24] -type PI PI
add mapped point i_rs2[23] i_rs2[23] -type PI PI
add mapped point i_rs2[22] i_rs2[22] -type PI PI
add mapped point i_rs2[21] i_rs2[21] -type PI PI
add mapped point i_rs2[20] i_rs2[20] -type PI PI
add mapped point i_rs2[19] i_rs2[19] -type PI PI
add mapped point i_rs2[18] i_rs2[18] -type PI PI
add mapped point i_rs2[17] i_rs2[17] -type PI PI
add mapped point i_rs2[16] i_rs2[16] -type PI PI
add mapped point i_rs2[15] i_rs2[15] -type PI PI
add mapped point i_rs2[14] i_rs2[14] -type PI PI
add mapped point i_rs2[13] i_rs2[13] -type PI PI
add mapped point i_rs2[12] i_rs2[12] -type PI PI
add mapped point i_rs2[11] i_rs2[11] -type PI PI
add mapped point i_rs2[10] i_rs2[10] -type PI PI
add mapped point i_rs2[9] i_rs2[9] -type PI PI
add mapped point i_rs2[8] i_rs2[8] -type PI PI
add mapped point i_rs2[7] i_rs2[7] -type PI PI
add mapped point i_rs2[6] i_rs2[6] -type PI PI
add mapped point i_rs2[5] i_rs2[5] -type PI PI
add mapped point i_rs2[4] i_rs2[4] -type PI PI
add mapped point i_rs2[3] i_rs2[3] -type PI PI
add mapped point i_rs2[2] i_rs2[2] -type PI PI
add mapped point i_rs2[1] i_rs2[1] -type PI PI
add mapped point i_rs2[0] i_rs2[0] -type PI PI
add mapped point i_imm[31] i_imm[31] -type PI PI
add mapped point i_imm[30] i_imm[30] -type PI PI
add mapped point i_imm[29] i_imm[29] -type PI PI
add mapped point i_imm[28] i_imm[28] -type PI PI
add mapped point i_imm[27] i_imm[27] -type PI PI
add mapped point i_imm[26] i_imm[26] -type PI PI
add mapped point i_imm[25] i_imm[25] -type PI PI
add mapped point i_imm[24] i_imm[24] -type PI PI
add mapped point i_imm[23] i_imm[23] -type PI PI
add mapped point i_imm[22] i_imm[22] -type PI PI
add mapped point i_imm[21] i_imm[21] -type PI PI
add mapped point i_imm[20] i_imm[20] -type PI PI
add mapped point i_imm[19] i_imm[19] -type PI PI
add mapped point i_imm[18] i_imm[18] -type PI PI
add mapped point i_imm[17] i_imm[17] -type PI PI
add mapped point i_imm[16] i_imm[16] -type PI PI
add mapped point i_imm[15] i_imm[15] -type PI PI
add mapped point i_imm[14] i_imm[14] -type PI PI
add mapped point i_imm[13] i_imm[13] -type PI PI
add mapped point i_imm[12] i_imm[12] -type PI PI
add mapped point i_imm[11] i_imm[11] -type PI PI
add mapped point i_imm[10] i_imm[10] -type PI PI
add mapped point i_imm[9] i_imm[9] -type PI PI
add mapped point i_imm[8] i_imm[8] -type PI PI
add mapped point i_imm[7] i_imm[7] -type PI PI
add mapped point i_imm[6] i_imm[6] -type PI PI
add mapped point i_imm[5] i_imm[5] -type PI PI
add mapped point i_imm[4] i_imm[4] -type PI PI
add mapped point i_imm[3] i_imm[3] -type PI PI
add mapped point i_imm[2] i_imm[2] -type PI PI
add mapped point i_imm[1] i_imm[1] -type PI PI
add mapped point i_imm[0] i_imm[0] -type PI PI

//output ports
add mapped point o_control_signal.rd[4] o_control_signal[rd][4] -type PO PO
add mapped point o_control_signal.rd[3] o_control_signal[rd][3] -type PO PO
add mapped point o_control_signal.rd[2] o_control_signal[rd][2] -type PO PO
add mapped point o_control_signal.rd[1] o_control_signal[rd][1] -type PO PO
add mapped point o_control_signal.rd[0] o_control_signal[rd][0] -type PO PO
add mapped point o_control_signal.fcs_opcode[2] o_control_signal[fcs_opcode][2] -type PO PO
add mapped point o_control_signal.fcs_opcode[1] o_control_signal[fcs_opcode][1] -type PO PO
add mapped point o_control_signal.fcs_opcode[0] o_control_signal[fcs_opcode][0] -type PO PO
add mapped point o_control_signal.iop o_control_signal[iop] -type PO PO
add mapped point o_control_signal.mem o_control_signal[mem] -type PO PO
add mapped point o_pc_load o_pc_load -type PO PO
add mapped point o_pc_ext[31] o_pc_ext[31] -type PO PO
add mapped point o_pc_ext[30] o_pc_ext[30] -type PO PO
add mapped point o_pc_ext[29] o_pc_ext[29] -type PO PO
add mapped point o_pc_ext[28] o_pc_ext[28] -type PO PO
add mapped point o_pc_ext[27] o_pc_ext[27] -type PO PO
add mapped point o_pc_ext[26] o_pc_ext[26] -type PO PO
add mapped point o_pc_ext[25] o_pc_ext[25] -type PO PO
add mapped point o_pc_ext[24] o_pc_ext[24] -type PO PO
add mapped point o_pc_ext[23] o_pc_ext[23] -type PO PO
add mapped point o_pc_ext[22] o_pc_ext[22] -type PO PO
add mapped point o_pc_ext[21] o_pc_ext[21] -type PO PO
add mapped point o_pc_ext[20] o_pc_ext[20] -type PO PO
add mapped point o_pc_ext[19] o_pc_ext[19] -type PO PO
add mapped point o_pc_ext[18] o_pc_ext[18] -type PO PO
add mapped point o_pc_ext[17] o_pc_ext[17] -type PO PO
add mapped point o_pc_ext[16] o_pc_ext[16] -type PO PO
add mapped point o_pc_ext[15] o_pc_ext[15] -type PO PO
add mapped point o_pc_ext[14] o_pc_ext[14] -type PO PO
add mapped point o_pc_ext[13] o_pc_ext[13] -type PO PO
add mapped point o_pc_ext[12] o_pc_ext[12] -type PO PO
add mapped point o_pc_ext[11] o_pc_ext[11] -type PO PO
add mapped point o_pc_ext[10] o_pc_ext[10] -type PO PO
add mapped point o_pc_ext[9] o_pc_ext[9] -type PO PO
add mapped point o_pc_ext[8] o_pc_ext[8] -type PO PO
add mapped point o_pc_ext[7] o_pc_ext[7] -type PO PO
add mapped point o_pc_ext[6] o_pc_ext[6] -type PO PO
add mapped point o_pc_ext[5] o_pc_ext[5] -type PO PO
add mapped point o_pc_ext[4] o_pc_ext[4] -type PO PO
add mapped point o_pc_ext[3] o_pc_ext[3] -type PO PO
add mapped point o_pc_ext[2] o_pc_ext[2] -type PO PO
add mapped point o_pc_ext[1] o_pc_ext[1] -type PO PO
add mapped point o_pc_ext[0] o_pc_ext[0] -type PO PO
add mapped point o_memory_data[31] o_memory_data[31] -type PO PO
add mapped point o_memory_data[30] o_memory_data[30] -type PO PO
add mapped point o_memory_data[29] o_memory_data[29] -type PO PO
add mapped point o_memory_data[28] o_memory_data[28] -type PO PO
add mapped point o_memory_data[27] o_memory_data[27] -type PO PO
add mapped point o_memory_data[26] o_memory_data[26] -type PO PO
add mapped point o_memory_data[25] o_memory_data[25] -type PO PO
add mapped point o_memory_data[24] o_memory_data[24] -type PO PO
add mapped point o_memory_data[23] o_memory_data[23] -type PO PO
add mapped point o_memory_data[22] o_memory_data[22] -type PO PO
add mapped point o_memory_data[21] o_memory_data[21] -type PO PO
add mapped point o_memory_data[20] o_memory_data[20] -type PO PO
add mapped point o_memory_data[19] o_memory_data[19] -type PO PO
add mapped point o_memory_data[18] o_memory_data[18] -type PO PO
add mapped point o_memory_data[17] o_memory_data[17] -type PO PO
add mapped point o_memory_data[16] o_memory_data[16] -type PO PO
add mapped point o_memory_data[15] o_memory_data[15] -type PO PO
add mapped point o_memory_data[14] o_memory_data[14] -type PO PO
add mapped point o_memory_data[13] o_memory_data[13] -type PO PO
add mapped point o_memory_data[12] o_memory_data[12] -type PO PO
add mapped point o_memory_data[11] o_memory_data[11] -type PO PO
add mapped point o_memory_data[10] o_memory_data[10] -type PO PO
add mapped point o_memory_data[9] o_memory_data[9] -type PO PO
add mapped point o_memory_data[8] o_memory_data[8] -type PO PO
add mapped point o_memory_data[7] o_memory_data[7] -type PO PO
add mapped point o_memory_data[6] o_memory_data[6] -type PO PO
add mapped point o_memory_data[5] o_memory_data[5] -type PO PO
add mapped point o_memory_data[4] o_memory_data[4] -type PO PO
add mapped point o_memory_data[3] o_memory_data[3] -type PO PO
add mapped point o_memory_data[2] o_memory_data[2] -type PO PO
add mapped point o_memory_data[1] o_memory_data[1] -type PO PO
add mapped point o_memory_data[0] o_memory_data[0] -type PO PO
add mapped point o_rd_output[31] o_rd_output[31] -type PO PO
add mapped point o_rd_output[30] o_rd_output[30] -type PO PO
add mapped point o_rd_output[29] o_rd_output[29] -type PO PO
add mapped point o_rd_output[28] o_rd_output[28] -type PO PO
add mapped point o_rd_output[27] o_rd_output[27] -type PO PO
add mapped point o_rd_output[26] o_rd_output[26] -type PO PO
add mapped point o_rd_output[25] o_rd_output[25] -type PO PO
add mapped point o_rd_output[24] o_rd_output[24] -type PO PO
add mapped point o_rd_output[23] o_rd_output[23] -type PO PO
add mapped point o_rd_output[22] o_rd_output[22] -type PO PO
add mapped point o_rd_output[21] o_rd_output[21] -type PO PO
add mapped point o_rd_output[20] o_rd_output[20] -type PO PO
add mapped point o_rd_output[19] o_rd_output[19] -type PO PO
add mapped point o_rd_output[18] o_rd_output[18] -type PO PO
add mapped point o_rd_output[17] o_rd_output[17] -type PO PO
add mapped point o_rd_output[16] o_rd_output[16] -type PO PO
add mapped point o_rd_output[15] o_rd_output[15] -type PO PO
add mapped point o_rd_output[14] o_rd_output[14] -type PO PO
add mapped point o_rd_output[13] o_rd_output[13] -type PO PO
add mapped point o_rd_output[12] o_rd_output[12] -type PO PO
add mapped point o_rd_output[11] o_rd_output[11] -type PO PO
add mapped point o_rd_output[10] o_rd_output[10] -type PO PO
add mapped point o_rd_output[9] o_rd_output[9] -type PO PO
add mapped point o_rd_output[8] o_rd_output[8] -type PO PO
add mapped point o_rd_output[7] o_rd_output[7] -type PO PO
add mapped point o_rd_output[6] o_rd_output[6] -type PO PO
add mapped point o_rd_output[5] o_rd_output[5] -type PO PO
add mapped point o_rd_output[4] o_rd_output[4] -type PO PO
add mapped point o_rd_output[3] o_rd_output[3] -type PO PO
add mapped point o_rd_output[2] o_rd_output[2] -type PO PO
add mapped point o_rd_output[1] o_rd_output[1] -type PO PO
add mapped point o_rd_output[0] o_rd_output[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point o_pc_load/q o_pc_load_reg/Q -type DLAT DLAT
add mapped point o_rd_output[0]/q o_rd_output_reg[0]/Q -type DLAT DLAT
add mapped point o_rd_output[1]/q o_rd_output_reg[1]/Q -type DLAT DLAT
add mapped point o_rd_output[2]/q o_rd_output_reg[2]/Q -type DLAT DLAT
add mapped point o_rd_output[3]/q o_rd_output_reg[3]/Q -type DLAT DLAT
add mapped point o_rd_output[4]/q o_rd_output_reg[4]/Q -type DLAT DLAT
add mapped point o_rd_output[5]/q o_rd_output_reg[5]/Q -type DLAT DLAT
add mapped point o_rd_output[6]/q o_rd_output_reg[6]/Q -type DLAT DLAT
add mapped point o_rd_output[7]/q o_rd_output_reg[7]/Q -type DLAT DLAT
add mapped point o_rd_output[8]/q o_rd_output_reg[8]/Q -type DLAT DLAT
add mapped point o_rd_output[9]/q o_rd_output_reg[9]/Q -type DLAT DLAT
add mapped point o_rd_output[10]/q o_rd_output_reg[10]/Q -type DLAT DLAT
add mapped point o_rd_output[11]/q o_rd_output_reg[11]/Q -type DLAT DLAT
add mapped point o_rd_output[12]/q o_rd_output_reg[12]/Q -type DLAT DLAT
add mapped point o_rd_output[13]/q o_rd_output_reg[13]/Q -type DLAT DLAT
add mapped point o_rd_output[14]/q o_rd_output_reg[14]/Q -type DLAT DLAT
add mapped point o_rd_output[15]/q o_rd_output_reg[15]/Q -type DLAT DLAT
add mapped point o_rd_output[16]/q o_rd_output_reg[16]/Q -type DLAT DLAT
add mapped point o_rd_output[17]/q o_rd_output_reg[17]/Q -type DLAT DLAT
add mapped point o_rd_output[18]/q o_rd_output_reg[18]/Q -type DLAT DLAT
add mapped point o_rd_output[19]/q o_rd_output_reg[19]/Q -type DLAT DLAT
add mapped point o_rd_output[20]/q o_rd_output_reg[20]/Q -type DLAT DLAT
add mapped point o_rd_output[21]/q o_rd_output_reg[21]/Q -type DLAT DLAT
add mapped point o_rd_output[22]/q o_rd_output_reg[22]/Q -type DLAT DLAT
add mapped point o_rd_output[23]/q o_rd_output_reg[23]/Q -type DLAT DLAT
add mapped point o_rd_output[24]/q o_rd_output_reg[24]/Q -type DLAT DLAT
add mapped point o_rd_output[25]/q o_rd_output_reg[25]/Q -type DLAT DLAT
add mapped point o_rd_output[26]/q o_rd_output_reg[26]/Q -type DLAT DLAT
add mapped point o_rd_output[27]/q o_rd_output_reg[27]/Q -type DLAT DLAT
add mapped point o_rd_output[28]/q o_rd_output_reg[28]/Q -type DLAT DLAT
add mapped point o_rd_output[29]/q o_rd_output_reg[29]/Q -type DLAT DLAT
add mapped point o_rd_output[30]/q o_rd_output_reg[30]/Q -type DLAT DLAT
add mapped point o_rd_output[31]/q o_rd_output_reg[31]/Q -type DLAT DLAT



//Black Boxes



//Empty Modules as Blackboxes
