
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Apr  1 2025 18:20:11 EDT (Apr  1 2025 22:20:11 UTC)

// Verification Directory fv/counter_top 

module counter_top(clk, rst, count);
  input clk, rst;
  output [7:0] count;
  wire clk, rst;
  wire [7:0] count;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, \count[0]_44 , n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_13;
  wire n_14, n_15, n_16, n_20, n_21, n_22, n_25, n_26;
  DFFR_X1 \count_reg[7] (.RN (n_21), .CK (clk), .D (n_22), .Q
       (count[7]), .QN (UNCONNECTED));
  XNOR2_X1 g231__2398(.A (n_20), .B (count[7]), .ZN (n_22));
  DFFR_X1 \count_reg[6] (.RN (n_21), .CK (clk), .D (n_25), .Q
       (count[6]), .QN (UNCONNECTED0));
  NAND2_X1 g235__5107(.A1 (n_15), .A2 (count[6]), .ZN (n_20));
  DFFR_X1 \count_reg[5] (.RN (n_21), .CK (clk), .D (n_16), .Q
       (count[5]), .QN (n_13));
  AOI21_X1 g237__4319(.A (n_15), .B1 (n_14), .B2 (n_13), .ZN (n_16));
  DFFR_X1 \count_reg[4] (.RN (n_21), .CK (clk), .D (n_26), .Q
       (count[4]), .QN (UNCONNECTED1));
  NOR2_X1 g240__8428(.A1 (n_14), .A2 (n_13), .ZN (n_15));
  NAND2_X1 g243__6783(.A1 (n_8), .A2 (count[4]), .ZN (n_14));
  DFFR_X1 \count_reg[3] (.RN (n_21), .CK (clk), .D (n_9), .Q
       (count[3]), .QN (n_6));
  AOI21_X1 g245__3680(.A (n_8), .B1 (n_7), .B2 (n_6), .ZN (n_9));
  NOR2_X1 g248__1617(.A1 (n_7), .A2 (n_6), .ZN (n_8));
  DFFR_X1 \count_reg[2] (.RN (n_21), .CK (clk), .D (n_5), .Q
       (count[2]), .QN (UNCONNECTED2));
  DFFR_X1 \count_reg[1] (.RN (n_21), .CK (clk), .D (n_4), .Q
       (count[1]), .QN (UNCONNECTED3));
  NAND2_X1 g251__2802(.A1 (n_2), .A2 (count[2]), .ZN (n_7));
  XNOR2_X1 g249__1705(.A (n_3), .B (count[2]), .ZN (n_5));
  AND2_X1 g253__5122(.A1 (n_3), .A2 (n_1), .ZN (n_4));
  INV_X1 g252(.A (n_3), .ZN (n_2));
  OR2_X1 g255__8246(.A1 (count[1]), .A2 (count[0]), .ZN (n_1));
  DFFR_X1 \count_reg[0] (.RN (n_21), .CK (clk), .D (\count[0]_44 ), .Q
       (count[0]), .QN (\count[0]_44 ));
  NAND2_X1 g256__7098(.A1 (count[1]), .A2 (count[0]), .ZN (n_3));
  INV_X1 g260(.A (rst), .ZN (n_21));
  XOR2_X1 g2(.A (n_15), .B (count[6]), .Z (n_25));
  XOR2_X1 g269(.A (n_8), .B (count[4]), .Z (n_26));
endmodule

