# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/Basys3_Master.xdc

# IP: ip/blk_mem_ram/blk_mem_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_ram || ORIG_REF_NAME==blk_mem_ram} -quiet] -quiet
