
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jan 28 2025 17:07:03 EST (Jan 28 2025 22:07:03 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, count);
  input clk, rst;
  output [7:0] count;
  wire clk, rst;
  wire [7:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  DFFRHQX1 \count_reg[7] (.RN (rst), .CK (clk), .D (n_13), .Q
       (count[7]));
  DFFRHQX1 \count_reg[6] (.RN (rst), .CK (clk), .D (n_12), .Q
       (count[6]));
  XNOR2X1 g184__2398(.A (count[7]), .B (n_11), .Y (n_13));
  OA21X1 g186__5107(.A0 (count[6]), .A1 (n_10), .B0 (n_11), .Y (n_12));
  DFFRHQX1 \count_reg[5] (.RN (rst), .CK (clk), .D (n_9), .Q
       (count[5]));
  NAND2X1 g188__6260(.A (count[6]), .B (n_10), .Y (n_11));
  AOI2BB1X1 g189__4319(.A0N (count[5]), .A1N (n_7), .B0 (n_10), .Y
       (n_9));
  DFFRHQX1 \count_reg[4] (.RN (rst), .CK (clk), .D (n_8), .Q
       (count[4]));
  DFFRHQX1 \count_reg[3] (.RN (rst), .CK (clk), .D (n_5), .Q
       (count[3]));
  AOI2BB1X1 g192__8428(.A0N (count[4]), .A1N (n_6), .B0 (n_7), .Y
       (n_8));
  AND2XL g191__5526(.A (count[5]), .B (n_7), .Y (n_10));
  AND2XL g194__6783(.A (count[4]), .B (n_6), .Y (n_7));
  AOI2BB1XL g195__3680(.A0N (count[3]), .A1N (n_4), .B0 (n_6), .Y
       (n_5));
  DFFRHQX1 \count_reg[2] (.RN (rst), .CK (clk), .D (n_3), .Q
       (count[2]));
  AND2XL g197__1617(.A (count[3]), .B (n_4), .Y (n_6));
  AOI2BB1X1 g198__2802(.A0N (count[2]), .A1N (n_2), .B0 (n_4), .Y
       (n_3));
  DFFRHQX1 \count_reg[1] (.RN (rst), .CK (clk), .D (n_1), .Q
       (count[1]));
  AND2XL g200__1705(.A (count[2]), .B (n_2), .Y (n_4));
  AOI2BB1X1 g201__5122(.A0N (count[1]), .A1N (count[0]), .B0 (n_2), .Y
       (n_1));
  NOR2BX1 g203__8246(.AN (count[1]), .B (n_0), .Y (n_2));
  DFFRX1 \count_reg[0] (.RN (rst), .CK (clk), .D (n_0), .Q (count[0]),
       .QN (n_0));
endmodule

