set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports bit]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports data_out]
set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
set_property PACKAGE_PIN R2 [get_ports bit]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

set_property PACKAGE_PIN U18 [get_ports clk]
set_property PACKAGE_PIN W19 [get_ports data_out]
set_property PACKAGE_PIN U16 [get_ports {data[0]}]
set_property PACKAGE_PIN E19 [get_ports {data[1]}]
set_property PACKAGE_PIN U19 [get_ports {data[2]}]
set_property PACKAGE_PIN V19 [get_ports {data[3]}]
set_property PACKAGE_PIN W18 [get_ports {data[4]}]
set_property PACKAGE_PIN U15 [get_ports {data[5]}]
set_property PACKAGE_PIN U14 [get_ports {data[6]}]
set_property PACKAGE_PIN V14 [get_ports {data[7]}]
